import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { DefaultLayout } from "../../../components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <AntdRegistry>
          <DefaultLayout>{children}</DefaultLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
